PARNAMI.MobileApp/PARNAMI.MobileApp/Controllers/PRController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.Mvc;
using SIMS.MM.MODEL;
using SIMS.MobileApprover.Helpers;

namespace SIMS.MobileApp.Controllers
{
    public class PRController : MobileApprover.Controllers.ApprovalControllerBase
    {

        public PRController() : base() { }

        public override void RegisterAllProviders(string username)
        {
            if (username == null)
            {
                if (Request == null) return;
                if (!Request.IsAuthenticated) return;
                var user = User.Identity.Name;
                if (user == null) return;
            }

                if (Roles.IsUserInRole("MI_CanVerify") || Roles.IsUserInRole("MI_AllRights")
                || Roles.IsUserInRole("admin") || Roles.IsUserInRole("dba"))
                this.Register("MI-Verify", new PRVerificationProvider());

            if (Roles.IsUserInRole("MI_CanApproveMI") || Roles.IsUserInRole("MI_AllRights")
                || Roles.IsUserInRole("admin") || Roles.IsUserInRole("dba"))
                this.Register("MI-Approve", new PRReqApprovalProvider());

            if (Roles.IsUserInRole("MI_CanApprovePO") || Roles.IsUserInRole("MI_AllRights")
                || Roles.IsUserInRole("admin") || Roles.IsUserInRole("dba"))
                this.Register("PO-Approve", new PRFinalApprovalProvider());
        }

        public override string GetApprovalText(string code)
        {
            if (code == "MI-Verify") return "Verify";
            if (code == "MI-Approve") return "Approve";
            if (code == "PO-Approve") return "Approve";
            return base.GetApprovalText(code);
        }
    }
}

PARNAMI.MobileApp/PARNAMI.MobileApp/Views/Shared/Details_MobileApprover.cshtml
@model object
@{
    ViewBag.Title = "Details";
    var detailedPVName = ViewBag.PartialViewName as String;
    int ApprovalForID = ViewBag.ApprovalForID;
    string ApprovalFor = ViewBag.ApprovalFor;
    string By = ViewBag.UserName;
    bool HasPVName = !String.IsNullOrWhiteSpace(detailedPVName);
}
<center>
    <span class="error">@ViewBag.err</span></center>
@if (HasPVName)
{
    @Html.Partial(detailedPVName, Model)
}
else
{
    @Html.DisplayForModel()
}
<div style="font-size: 8px;">
    <div>
        @using (Html.BeginForm("Approve", "PR", new { ID = @ApprovalForID, By = By, For = @ApprovalFor, boolvalue = true }, FormMethod.Get))
        {
            <b><i>Approval Remarks:</i></b>
            <textarea style="width: 100%; height: 30px; max-height: 50px" name="Comment" id="Comment"></textarea>
            <input type="submit" value="@ViewBag.approve" data-icon="check" data-iconpos="left" data-inline="true"/>
            @*<a href="@Url.Action("Approve", new { ID = @ApprovalForID, By = By, For = @ApprovalFor, boolvalue = true })" data-role="button" data-icon="check" data-iconpos="left" data-inline="true">@ViewBag.approve</a>
            <br />*@
        }
        @using (Html.BeginForm("Approve", "PR", new { ID = @ApprovalForID, By = By, For = @ApprovalFor, boolvalue = false }, FormMethod.Get))
        {
            <b><i>Rejection Remarks:</i></b>
            <textarea style="width: 100%; height: 30px; max-height: 50px" name="Comment" id="Comment"></textarea>
            <input type="submit" value="@ViewBag.reject" data-icon="delete" data-iconpos="left" data-inline="true"/>
            @*<a href="@Url.Action("Approve", new { })" data-role="button" data-icon="delete" data-iconpos="left" data-inline="true">@ViewBag.reject</a> *@
        }
    </div>
    <a href="@Url.Action("Index")" data-role="button" data-icon="back" data-iconpos="left">
        All Approvals</a>
</div>

PARNAMI.MobileApp/PARNAMI.MobileApp/Views/Shared/GetSiteWiseStock.cshtml
@model IEnumerable<SIMS.MM.DAL.GetDetailedStockReportResult>
@{
    ViewBag.Title = "Current Stock";
}
<h2>
    Current Stock</h2>
<p>
    <a href="javascript:window.history.back()">Back</a>
</p>
<table>
    <tr>
        <th>
            Site
        </th>
        <th>
            Stock
        </th>
        <th>
            Size
        </th>
        <th>
            Brand
        </th>
        <th>
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            @if (ViewBag.siteid == item.SiteID)
            {
                <td style='background: Orange;'>
                    @Html.DisplayFor(modelItem => item.Site)
                </td>
            }
            else
            { 
                <td>
                    @Html.DisplayFor(modelItem => item.Site)
                </td>
            }
            @if (ViewBag.size == item.SizeID && ViewBag.brand == item.BrandID && ViewBag.siteid == item.SiteID)
            {
                <td style='background:Orange;'>
                    @Html.DisplayFor(modelItem => item.ClosingBalance)
                </td>
                <td style='background: Orange;'>
                    @Html.DisplayFor(modelItem => item.Size)
                </td>
                <td style='background: Orange;'>
                    @Html.DisplayFor(modelItem => item.Brand)
                </td>
            }
            else
            {
                <td>
                    @Html.DisplayFor(modelItem => item.ClosingBalance)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Size)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Brand)
                </td>
            }
        </tr>
    }
</table>

PARNAMI.MobileApp/PARNAMI.MobileApp/Views/Shared/Index_MobileApprover.cshtml
@model IEnumerable<SIMS.MobileApprover.ApprovalRequestModel>
@{
    if (Model.Count() == 0)
    {
        ViewBag.Title = "No Approvals are Pending!";
    }
    else
    {
        ViewBag.Title = "Pending Approvals :";
    }
}
<h2>@ViewBag.Title</h2>
@foreach (var item in Model)
{
    @Html.DisplayFor(model => item);
}
@*<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ApprovalFor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApprovalForID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApprovalForRef)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IconPath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShortDetalils)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Details)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comment)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ApprovalFor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApprovalForID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApprovalForRef)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IconPath)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ShortDetalils)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Details)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comment)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>*@ 

PARNAMI.MobileApp/PARNAMI.MobileApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title>
        <meta name="viewport" content="width=device-width" />
        <link href="@Url.Content("~/favicon.ico")" rel="shortcut icon" type="image/x-icon" />
        <link href="@Url.Content("~/Content/jquery.mobile.theme-1.1.0.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/jquery.mobile.structure-1.1.0.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/jquery.mobile-1.1.0.css")" rel="stylesheet" type="text/css" />
        <script src="@Url.Content("~/Scripts/modernizr-2.5.3.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery-1.7.1.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery.mobile-1.1.0.js")" type="text/javascript"></script>
        <link href="../../Content/Site.css" rel="stylesheet" type="text/css" />
        @RenderSection("scripts", required: false)
    </head>
    <body>
        <div data-role="page" data-theme="b">
            <div data-role="header">
                @if (IsSectionDefined("Header")) {
                    @RenderSection("Header")
                } else {
                    <h1>@ViewBag.Title</h1>
                    @Html.Partial("_LoginPartial")
                }
            </div>
            <div data-role="content">
                @RenderBody()
            </div>
        </div>
    </body>
</html>

PARNAMI.MobileApp/PARNAMI.MobileApp/Views/Shared/_LogOnPartial.cshtml
@if (Request.IsAuthenticated)
{
    <text>Welcome <strong>@User.Identity.Name</strong>! 
    [ @Html.ActionLink("Log Off", "LogOff", "Account", new { Title = "Log Out" })
    ]</text>
}
else
{
    @:[ @Html.ActionLink("Log On", "LogOn", "Account", new { Title = "Log In" }) ]
}